feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  # tracing:
  #   sampling:
  #     probability: 1.0
resilience4j.:
circuitbreaker:
  instances:
    
resilience4j:
  circuitbreaker:
    instances:
      carServiceCB:
        register-health-indicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      rentalCompanyServiceCB:
        register-health-indicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      bookingServiceCB:
        register-health-indicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      rentalCompanyClient:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException


spring:
  datasource:
    url: jdbc:postgresql://car_rental_1zfk_user:L82zaSCCdWJFdYK7BEH4z5VNdrUMGO2I@dpg-d11au16mcj7s73a1q1kg-a.oregon-postgres.render.com/car_rental_1zfk
    username: car_rental_1zfk_user
    password: L82zaSCCdWJFdYK7BEH4z5VNdrUMGO2I
    driver-class-name: org.postgresql.Driver
  hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000         # 30 seconds
      max-lifetime: 1800000       # 30 minutes
      connection-timeout: 30000   # 30 seconds




  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # zipkin:
  #   base-url: http://localhost:9411
  #   enabled: true
  #   service:
  #     name: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 10         # frequency to fetch registry
    eureka-service-url-poll-interval-seconds: 60 # polling interval for Eureka

  instance:
    lease-renewal-interval-in-seconds: 10        # how often this instance renews its lease
    lease-expiration-duration-in-seconds: 30     # how long Eureka waits before evicting this instance
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}  # unique ID


logging:
  level:
    com.netflix.discovery: WARN
    org.springframework.cloud.netflix.eureka: WARN
    org.springframework.web: INFO
  # pattern:
  #   level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
