feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: false  # Disable Hystrix if using Resilience4j

management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      carService:
        register-health-indicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

spring:
  datasource:
    url: jdbc:postgresql://yamanote.proxy.rlwy.net:48248/railway
    username: postgres
    password: EbWmhfvRojvWIULVkTcKTvvcseZxYecN
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    preferIpAddress: true
    metadataMap:
      instanceId: "${spring.application.name}:${spring.application.instance_id:${random.value}}"

logging:
  level:
    com.netflix.discovery: WARN
    org.springframework.cloud.netflix.eureka: WARN
    org.springframework.web: INFO
